version: '3.8'

services:
  nodejs-app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    env_file:
      - stack.env 
    command: ["npm", "start"]

